version: '3.8'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: sample
      MYSQL_USER: basic
      MYSQL_PASSWORD: sample
    volumes:
      - ./db:/var/lib/mysql

  adminer:
   image: adminer
   restart: always
   depends_on: 
     - mysql
   ports:
     - 8080:8080
